language: node_js
node_js:
  - stable

stages:
  - build
  - name: deploy_dev
    if: branch = master # TODO: A dev branch is probably better

jobs:
  include:
    - stage: build

    - stage: deploy_dev
      script:
        - gem install package_cloud
        - bash .ci/publish_dev.sh
